
services:
  lavagna:
    container_name: lavagna
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      DB_URL: "jdbc:postgresql://db:5432/lavagna"
      DB_USER: "lavagna_user"
      DB_PASS: "lavagna_pass"
      SPRING_PROFILE: "prod"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: lavagna_db
    environment:
      POSTGRES_DB: "lavagna"
      POSTGRES_USER: "lavagna_user"
      POSTGRES_PASSWORD: "lavagna_pass"
    volumes:
      - db_data:/var/lib/postgresql/data