version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: lavagna-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  lavagna:
    build:
      context: .
      dockerfile: Dockerfile.light
    container_name: lavagna-app
    depends_on:
      - mysql
    ports:
      - "${APP_PORT}:8080"
    environment:
      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: ${DB_HOST}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
  nginx:
      image: nginx:alpine
      container_name: lavagna-nginx
      ports:
        - "80:80"
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./project/src/main/webapp:/webapp
      depends_on:
        - lavagna

volumes:
  mysql_data:
